name: Preview release

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, labeled, ready_for_review]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number }}
  cancel-in-progress: true
        
permissions:
  contents: read
  actions: write
  
env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
  FORCE_COLOR: true
  ASTRO_TELEMETRY_DISABLED: true
  # 7 GiB by default on GitHub, setting to 6 GiB
  # https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources
  NODE_OPTIONS: --max-old-space-size=6144

jobs:
  preview:
    if: |
      ${{ github.repository_owner == 'withastro' && github.event.issue.pull_request && contains(github.event.pull_request.labels.*.name, 'pr: preview') }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      issues: write
      pull-requests: write
    name: Publish preview release
    timeout-minutes: 5
    steps:
      - name: Disable git crlf
        run: git config --global core.autocrlf false
  
      - name: Checkout
        uses: actions/checkout@v4
  
      - name: Setup PNPM
        uses: pnpm/action-setup@v3
  
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "pnpm"
  
      - name: Install dependencies
        run: pnpm install
  
      - name: Build Packages
        run: pnpm run build
  
      - name: Publish packages
        run: pnpx pkg-pr-new publish --pnpm './packages/*' './packages/integrations/*'
